name: live_coding
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  dio: ^5.2.0
  go_router: ^7.1.1
  remixicon: ^1.0.0
  get_it: ^7.6.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: false
  generate: true
  assets:
    - assets/
